### ISSUE TITLE
Remove `fog_ledger_test_infra::MockLedger`

### ISSUE THREAD

**Issue by garbageslam** [mobilecoinfoundation/mobilecoin#1005]
We already have a Mock Ledger object among the `mc-ledger-db` crates, we don't need a second MockLedger object

Possibly, remove the entire `mc-fog-ledger-test-infra` crate

**Comment by remoun** [comment]
FWIW I ended up improving `mc_ledger_db::MockLedger` in #2052, which could help this work.

**Comment by jcape** [comment]
Work already done.
