### ISSUE TITLE
Track down source of flakey unit test

### ISSUE THREAD

**Issue by jcape** [mobilecoinfoundation/mobilecoin#1063]
Occasionally, our unit tests fails with the following error.

```json
{
  "type": "test",
  "event": "timeout",
  "name":  "api::client_api_service::client_api_tests::test_client_tx_propose_tx_over_capacity"
}
```
The logged message is:
```
Too long with no output (exceeded 10m0s): context deadline exceeded
```

This appears to be intermittent, but we should look into why this is happening before we release 1.4. If this is a real problem (and not just CI infrastructure hork), my intuition/random wild-assed guess is that Rayon 1.3 -> 1.5.1 broke an assumption we were relying on about when threads are getting woken up.

**Comment by remoun** [comment]
Seems to be gone with GHA
