### ISSUE TITLE
Consensus & Fog binaries should emit build info on `-v` or something

### ISSUE THREAD

**Issue by cbeck88** [mobilecoinfoundation/mobilecoin#1114]
When trying to investigate what revision is deployed, one way to do it is look at logs:

```
2021-10-20 19:54:51.252264804 UTC INFO test_client started: { "GIT_COMMIT": "d9ff9557-modified", "PROFILE": "debug", "DEBUG": "true", "OPT_LEVEL": "0", "DEBUG_ASSERTIONS": "false", "TARGET_ARCH": "x86_64", "TARGET_OS": "linux", "TARGET_FEATURE": "adx,aes,avx,avx2,bmi1,bmi2,cmpxchg16b,ermsb,f16c,fma,fxsr,lzcnt,movbe,pclmulqdq,popcnt,rdrand,rdseed,sse,sse2,sse3,sse4.1,sse4.2,ssse3,xsave,xsavec,xsaveopt,xsaves", "RUSTFLAGS": "?", "SGX_MODE": "HW", "IAS_MODE": "PROD" }, mc.app: test_client, mc.module: mc_common::logger::loggers, mc.src: common/src/logger/loggers/mod.rs:249
```

but this is only logged at the beginning and usually isn't retained.

It would be great if we could go into the container and run `./consensus-service -v` and it would tell us this info, and similarly for fog services

**Comment by remoun** [comment]
Impl idea: Since we want this for several binaries, we can define something like `trait ParserWithBuildInfo: clap::Parser`, and provide a default impl for all `Parser`s, so that callers can just `use ParserWithBuildInfo` instead of `use clap::Parser`, and the rest of the code looks the same.

**Comment by nick-mobilecoin** [comment]
I've got 2 possible implementations:
* https://github.com/remoun/mobilecoin/compare/replace-structopt...nick-mobilecoin:cli-version_info  Provides a static string for the `version` argument to the clap attribute.
* https://github.com/remoun/mobilecoin/compare/replace-structopt...nick-mobilecoin:cli-version-trait Implements a trait with default impl for a `ParserWithBuildInfo`

```
$./target/debug/consensus-service -V
consensus_service get_crate_stuff commit: b6d5a688-modified
```
I'm very open to suggestions as I've got a good hunch there are probably cleaner ways to do this in rust.

I also noticed the git sha doesn't seem to update reliably (at least for incrementals).
```
$ git status
On branch cli-version_info
Your branch is up to date with 'nick/cli-version_info'.

nothing to commit, working tree clean
$ cargo build
warning: Compiling mc-sgx-slog for IAS dev mode
warning: Compiling mc-sgx-urts for SGX simulation mode
warning: Linking rust mc-sgx-urts against sgx_urts_sim
warning: Compiling mc-attest-untrusted for SGX simulation mode
warning: Linking rust mc-attest-untrusted against sgx_epid_sim
warning: Compiling mc-attest-net for SGX simulation mode
warning: Compiling mc-attest-net for IAS dev mode
warning: Compiling mc-consensus-service for SGX simulation mode
warning: Signed enclave consensus-enclave not provided, trying to sign it...
warning: Unsigned enclave consensus-enclave not provided, trying to link a new one...
warning: Generating single-use key for insecure, one-shot signature of consensus-enclave
warning: Signed enclave ingest-enclave not provided, trying to sign it...
warning: Unsigned enclave ingest-enclave not provided, trying to link a new one...
warning: Generating single-use key for insecure, one-shot signature of ingest-enclave
warning: Signed enclave ledger-enclave not provided, trying to sign it...
warning: Unsigned enclave ledger-enclave not provided, trying to link a new one...
warning: Generating single-use key for insecure, one-shot signature of ledger-enclave
warning: Signed enclave view-enclave not provided, trying to sign it...
warning: Unsigned enclave view-enclave not provided, trying to link a new one...
warning: Generating single-use key for insecure, one-shot signature of view-enclave
   Compiling mc-consensus-service v1.3.0-pre0 (/home/nick/git/mobilecoin/consensus/service)
    Finished dev [unoptimized + debuginfo] target(s) in 15.81s
$ ./target/debug/consensus-service -V
consensus_service get_crate_stuff commit: b6d5a688-modified
$ git log
commit b508012148c2c96ac22c649caea8ce953233505f (HEAD -> cli-version_info)
Author: Nick Santana <nick@mobilecoin.com>
Date:   Mon Mar 21 16:13:31 2022 -0700

    Just committing for fun

    simplify the version info

commit 2e08882c7a1536511331c0ef6974add05528e22b (nick/cli-version_info)
Author: Nick Santana <nick@mobilecoin.com>
Date:   Mon Mar 21 14:34:29 2022 -0700

    hmmm

    Have a basic implementation of the report string output as version

commit b6d5a688ef139ba142f586400c07683b3c674171
Author: Nick Santana <nick@mobilecoin.com>
```

@eranrund, I haven't had a chance to look into the grpc endpoints.  I'm still spinning up and don't understand many of the pieces. Are you thinking the `mc_util_build_info` dependency should be avoided, or is there some nicer formatting that the `BuildInfo` provides?

**Comment by eranrund** [comment]
> @eranrund, I haven't had a chance to look into the grpc endpoints. I'm still spinning up and don't understand many of the pieces. Are you thinking the `mc_util_build_info` dependency should be avoided, or is there some nicer formatting that the `BuildInfo` provides?

No, `mc_util_build_info` is what you need to implement `-v`. What I was point at is that we are currently able to get the git revision of a given service over GRPC, if it exposes the `BuildInfo` service - which should be easier to use than having to run a command on a container to find out what version is present on it.
