### ISSUE TITLE
Improve log message when watcher is "syncing signatures"

### ISSUE THREAD

**Issue by jcape** [mobilecoinfoundation/mobilecoin#1293]
When watcher becomes stuck because it cannot download blocks for a particular node, it should log which configured node it cannot synchronize from.

**Comment by iamalwaysuncomfortable** [comment]
This seems to be already implemented

This logs a WatcherError enum option: https://github.com/mobilecoinfoundation/mobilecoin/blob/master/watcher/src/watcher.rs#L196-L205

And this populates it with source info:
https://github.com/mobilecoinfoundation/mobilecoin/blob/master/watcher/src/watcher.rs#L219-L235

Local network test verifies that but are likely not exhaustive. If there's a log aggregator online, I can explicitly check if any watcher logs aren't reporting url correctly
