### ISSUE TITLE
Lint requires sgx

### ISSUE THREAD

**Issue by wjuan-mob** [mobilecoinfoundation/mobilecoin#1304]
![image](https://user-images.githubusercontent.com/89989823/149024871-27360daa-3680-4881-a627-ba8655d9754a.png)
Lint requires SGX to run, so if run outside of docker, it throws an error about could not find SGX libraries. It should be that you just need to provide a CONSENSUS_ENCLAVE_CSS file via environment.

**Comment by jcape** [comment]
This is coming out of https://github.com/mobilecoinofficial/full-service/pull/220. The fix here is to change the build to check for SGX only if it's actually needed.

**Comment by eranrund** [comment]
Isnt the solution here for full-service to not lint `mobilecoin`?
Do you ever run into this issue when running lint.sh inside the `mobilecoin` repo?

**Comment by jcape** [comment]
> 



> Isnt the solution here for full-service to not lint `mobilecoin`? Do you ever run into this issue when running lint.sh inside the `mobilecoin` repo?

Yes, this issue was ultimately caused by running lint.sh against `mobilecoin`, which would trigger attempted enclave builds.
