### ISSUE TITLE
Fog View and Ledger "Readiness"

### ISSUE THREAD

**Issue by jcape** [mobilecoinfoundation/mobilecoin#1399]
Fog's View and Leger services should not be serving requests before they have "caught up" with postgres, so this information should be reported over gRPC in such a way that orchestration tools (e.g. kubernetes) can check for "readiness" before routing traffic to a new instance.

While loading, view and ledger should not serve requests, and instead respond to clients with `UNAVAILABLE`.

**Definition of Done**

Both services are reporting state, and there is an integration test which will test a restart / load-from-scratch scenario.

**Next Steps**

Ops must chose the form of the destroyer.

**Comment by samdealy** [comment]
This issue was fixed by #1336.
