### ISSUE TITLE
Update rust to more recent nightly

### ISSUE THREAD

**Issue by jcape** [mobilecoinfoundation/mobilecoin#1408]
We should update the rust nightly we are using to something that works on all our dependencies, and includes the CVE fixe from 1.58.1.

- [x] #1369

**Comment by remoun** [comment]
We might want to strip debug info from binaries in release mode, per the [1.59release notes](https://blog.rust-lang.org/2022/02/24/Rust-1.59.0.html)

```toml
[profile.release]
strip = "debuginfo"
```
