### ISSUE TITLE
Support view database larger than working memory

### ISSUE THREAD

**Issue by jcape** [mobilecoinfoundation/mobilecoin#1434]
The original discussion:

> Currently, the fog ocall oram storage code just uses malloc to allocate storage for (encrypted) oram blocks outside of enclave. It would be better to make it so that, e.g. fog view can be passed /dev/sdb on command line and it will try to open this and read /write to it using `io_uring` or something like this.
> 
> Our machines in Azure have a many GB sized "[local temporary disk](https://docs.microsoft.com/en-us/azure/virtual-machines/dcv3-series#dcdsv3-series-technical-specifications)." I believe that this is just an [SSD attached to the host in /dev/sdb or something](https://docs.microsoft.com/en-us/azure/virtual-machines/azure-vms-no-temp-disk).
> 
> The software side is to try to write the code that would use `io_uring` in the fastest possible way (similar to e.g. a database). The ops side is to try mounting the local temporary disk into the container, then try to speed test it and see if we get interesting numbers.
> 
> A good comparison may be to see how people who e.g. run a database inside of kubernetes, manage to give the database the best latency to read and write to the disk, and what incantations they actually give to kubernetes to do that.

I'd offer that I don't really care whether `io_uring` is actually used, even "swap on local temporary disk" could be a stop-gap measure---the main thing is being able to test these scenarios out and determine what the MVP is going to be, how far we can take that, and what advantages we're going to see by using the raw block device instead. This is meant as a tracking issue for that effort:

- [x] Get a network where we can test fog view running out of memory.
- [ ] Investigate fog view with large transaction sizes using the local temp disk as swap.
- [ ] Investigate a more controlled `mmap` (since `malloc` will simply fallback to anonymous `mmap` above, IIRC, 2MB) implementation
- [ ] Investigate various `io_uring` crates and implementations.

**Comment by jgreat** [comment]
We're currently constrained to  Standard_DC4s_v2 (4 core, 16GB) series VMs.  https://docs.microsoft.com/en-us/azure/virtual-machines/dcv2-series. 

They do have temp storage that gets set up at (/dev/sdb1) /mnt. I'm not sure this is the "high performance" local ssd. The Ephemeral OS disk is a different feature. 

If possible, I'd recommend that we do not try and force usage of disk by just filling up the memory and expecting the system to put the extra into swap.  The problem with pushing the system into using swap like that is the kernel (kswapd) will get more and more aggressive spending cpu time reviewing swap pages and trying to free up system memory.  We can tune swappiness and the various behaviors, but that's going to be tricky and require a lot of testing.

Do we know what the I/O characteristics are going to be. Random vs Sequential, Write vs Read, block size?

### Some basic testing of `/mnt` with fio:

Sequential Read 1M blocks: 
```
fio --name TEST --eta-newline=5s --filename=temp.file --rw=randrw --size=2g --io_size=10g --blocksize=64k --ioengine=libaio --fsync=1 --iodepth=1 --direct=1 --numjobs=1 --runtime=60 --group_reporting

read: IOPS=63, BW=63.8MiB/s (66.9MB/s)(3860MiB/60487msec)
```

Sequential Write 1M blocks:
```
fio --name TEST --eta-newline=5s --filename=temp.file --rw=write --size=2g --io_size=10g --blocksize=1024k --ioengine=libaio --fsync=10000 --iodepth=32 --direct=1 --numjobs=1 --runtime=60 --group_reporting

write: IOPS=63, BW=63.8MiB/s (66.9MB/s)(3857MiB/60462msec)
```

For reference, same tests on my laptop nvme with full disk encryption:
```
read: IOPS=2144, BW=2145MiB/s (2249MB/s)(10.0GiB/4775msec)
write: IOPS=2289, BW=2290MiB/s (2401MB/s)(10.0GiB/4472msec)
```

**Comment by jcape** [comment]
Will retest with Circuit ORAM

**Comment by jcape** [comment]
We can retest, but it doesn't look like this will be feasible without new research.
