### ISSUE TITLE
Fog Overseer CD

### ISSUE THREAD

**Issue by jcape** [mobilecoinfoundation/mobilecoin#1482]
This is a tracking issue for getting Fog Overseer into our dev network and CD deployments.

**Comment by samdealy** [comment]
(This issue was prematurely closed by GitHub)

**Comment by samdealy** [comment]
Fog Overseer has been deployed to CD. There are some things that need to be addressed (e.g. start overseer as disableed before fog ingest is running and then enable it to ensure that it doesn't initiate automatic failover), but those will be part of a new issue.
