### ISSUE TITLE
Maybe there is a bug in fog/ocall_oram_storage/trusted/src/lib.rs

### ISSUE THREAD

**Issue by AmbitionXiang** [mobilecoinfoundation/mobilecoin#1576]
Hi, there.

At line 331, `if idx == first_treetop_index` seems to be  `if idx == first_treetop_index - 1`? Otherwise, the check against trusted roots is never encountered.

**Comment by garbageslam** [comment]
I am still investigating and started working on this -- I think you are right that there is an off by one mistake that makes the merkle root check not happen. I will finish writing a patch and tests soon.

Thanks for reporting this issue!

**Comment by AmbitionXiang** [comment]
You're welcome!
