### ISSUE TITLE
Gift Code Rework - MCIP #32

### ISSUE THREAD

**Issue by garbageslam** [mobilecoinfoundation/mobilecoin#1735]
Implement "Gift Code" functionality that allows the owner of a MobileCoin account to send MobileCoin to others who may not yet have a MobileCoin account or  MobileCoin gifts that can be claimed in a "Red Envelope" style.

The underlying MCIP outlining the design of this feature can be found here: https://github.com/mobilecoinfoundation/mcips/pull/32

The steps to gift code implementation are roughly:
- [x] #1851
- [x] #1852
- [x] #1890
- [x] #1891
- [x] #2001 
- [x] #2003
- [x] #1945

**Comment by iamalwaysuncomfortable** [comment]
This feature will be fully tested when the priority for using it becomes elevated
