### ISSUE TITLE
Fix CI invocations

### ISSUE THREAD

**Issue by garbageslam** [mobilecoinfoundation/mobilecoin#1759]
The `run-fog-tests` step is supposed to run tests for packages in `mc-fog-*` excluding `mc-fog-ingest-*`:

https://github.com/mobilecoinfoundation/mobilecoin/blob/810b75a0628ba0ea79ff65b924ce505a333870f6/.circleci/config.yml#L395

However, from observing CI times, this takes 45 minutes and appears to run all tests including `mc-transaction-core` and `mc-watcher`.

TODO: Figure out what is the right way to test only this set of packages, perhaps this is a bug in cargo, or there is another way in cargo that this is supposed to work. Or we should not use cargo's flags, and instead grep through the workspace `Cargo.toml` ourselves and then invoke cargo like `cargo test -p foo -p bar -p baz`.

**Comment by remoun** [comment]
We could list the packages with `cargo test -p` and grep the resulting list of packages, e.g. `cargo test -p 2>&1 | grep mc-fog | grep -v mc-fog-ingest | awk '{print "-p " $1}'`

**Comment by remoun** [comment]
> We could list the packages with `cargo test -p` and grep the resulting list of packages, e.g. `cargo test -p 2>&1 | grep mc-fog | grep -v mc-fog-ingest | awk '{print "-p " $1}'`

I ended up using this approach in #1693.  I think we can close this in favor of #1687.
