### ISSUE TITLE
Consensus enclave should disallow zero-value outputs of token ids that aren't configured yet

### ISSUE THREAD

**Issue by garbageslam** [mobilecoinfoundation/mobilecoin#1868]
In mixed token types PR, we added the ability for the Tx to specify a token id per output and pseudo-output, but consensus enclave doesn't check that those are actually allowed token ids right now. The user cannot do anything with this except create zero value outputs with funky token ids, but there is no good reason to allow that to happen right now, so we should probably prohibit it.

It may make certain optimizations harder if it actually happens on the chain, and if we decide its useful to allow this then we can remove this check later.

_Originally posted by @garbageslam in https://github.com/mobilecoinfoundation/mobilecoin/pull/1827#discussion_r860051051_

**Comment by eranrund** [comment]
Interesting, can you create outputs without any inputs if the output amount is zero?

**Comment by garbageslam** [comment]
I think the Tx is rejected if there are actually zero inputs, but as long as there is at least one valid input, you can mint zero value outputs I think

**Comment by eranrund** [comment]
I also wonder if you can have a few legitimate non-zero inputs and outputs for token id X and then zero-amount outputs for token id Y?

**Comment by eranrund** [comment]
Seems like yeah, that could actually result in creation of arbitrary token ids with zero amount and we should not allow that.

**Comment by garbageslam** [comment]
Yeah, I guess it might confuse the clients also, depends what they do when they see a token id they don't know

**Comment by eranrund** [comment]
Nice catch. Seems like if the enclave does see the token_ids, having it refuse token_ids that do not have a minimum fee configured is a good way to prevent this abuse.
