### ISSUE TITLE
Re-evalaute hasher-builder

### ISSUE THREAD

**Issue by iamalwaysuncomfortable** [mobilecoinfoundation/mobilecoin#1937]
Hasher Builder was built to introduce predictable randomness into our hashing schemes, avoid hash collisions, and work in a no-std environment. However, it was built a while ago on the Sip-13 hashing algorithm. As time has evolved, hashing schemes have as well, so we may consider re-auditing the algorithm and ct behind hasher builder to speed it up and re-audit its security properties.

**Comment by garbageslam** [comment]
I would suggest that, maybe this should just track whatever the rust stdlib hasher builder is doing? I would have just reused their thing if there was a way to make it use `mc-crypto-rand`

**Comment by iamalwaysuncomfortable** [comment]
Absolutely agreed. When I looked into other hash algos in rust I saw some features that might be worth comparing to Sip13. I consider this more of a thing to keep in the mental backlog rather than anything that's currently urgent or will really ever be necessary.
