### ISSUE TITLE
Make a way to make gift code outputs that has fog hint addressed to the view pubkey for default subaddress, similar to how `.add_change_output` works

### ISSUE THREAD

**Issue by garbageslam** [mobilecoinfoundation/mobilecoin#2003]
The test code for the gift code memo builders does send funded gift code outputs to the gift code subaddress, but it does this by using `.add_outputs(&reserved_destinations.gift_code_address`. 

This does not ultimately lead to a call in the transaction builder that makes the output owned by gift code address but with fog hint for the default subaddress. That means that fog users won't actually find it.

To fix this, we should either make a `.add_gift_code_output` function on transaction builder, or make a special transaction builder for the gift code funding operations.

I am not sure right now which direction is better, I think both directions have merit

_Originally posted by @garbageslam in https://github.com/mobilecoinfoundation/mobilecoin/pull/1977#discussion_r876543940_

**Comment by iamalwaysuncomfortable** [comment]
It seems as if we do want an ability to send a transaction to oneself at a different subaddress and have it be resolvable by FOG. In the "Mechanics of Mobilecoin" it talks about scenarios where Alice & Bob might want to use different subaddresses for various reasons, so my vote would be adding transaction builder method for sending transactions to oneself? Like .add_output_to_self()?
