### ISSUE TITLE
`./mob prompt` creates a new docker container on each run

### ISSUE THREAD

**Issue by david1alvarez** [mobilecoinfoundation/mobilecoin#2012]
`./mob prompt` creates new docker containers each time it is run, and doesn't clean them up. By passing `--rm` to the docker container creation flow, docker will clean up containers after use. We should either streamline the process of reusing an already created docker container, or streamline the process of cleaning up old containers automatically.

**Comment by garbageslam** [comment]
I think we can just add this flag: https://docs.docker.com/engine/reference/run/#clean-up---rm

**Comment by garbageslam** [comment]
I think we should optimize for ease of workflow -- making an anonymous container and removing it when we exit seems the simplest

**Comment by garbageslam** [comment]
i just ran `docker system prune`:

```
Total reclaimed space: 77.44GB
```

:open_mouth:

**Comment by remoun** [comment]
`mob` now cleans up the container it creates.
