### ISSUE TITLE
Fog View Router

### ISSUE THREAD

**Issue by jcape** [mobilecoinfoundation/mobilecoin#2028]
- [x] #2097
- [x] #2254
- [x] #2253 
- [x] #2233
- [x] #2256
- [x] #2255
- [x] #2435
- [x] #2395
- [x] #2836
- [x] #2837
- [x] #2930
- [x] #2838
- [x] #3177
- [x] It was determined that #3178 is not needed for the initial release

**Comment by nick-mobilecoin** [comment]
Done in #3297
