### ISSUE TITLE
AVR-on-Chain in 1.3

### ISSUE THREAD

**Issue by jcape** [mobilecoinfoundation/mobilecoin#2104]
- [x] MCIP for BlockVersion 3 requiring `BlockMetadata`: https://github.com/mobilecoinfoundation/mcips/pull/43
- [x] #1403
  - [x] #2067
  - [x] #2058 
  - [x] #2052
  - [x] #2205
  - [x] #2216

**Comment by remoun** [comment]
This could be helpful for collecting SCP signing keys from consensus nodes: https://github.com/wiberlin/mc-crawler
