### ISSUE TITLE
Cannot switch to the new release: reference is not a tree

### ISSUE THREAD

**Issue by fmira21** [mobilecoinfoundation/mobilecoin#2544]
Hi guys!

I am trying to build the node straight from your repo according to my actual pipeline - including checking out to the latest reference `0f09862109fa8c3749012ffed355eb25eed775d6`.

Unfortunately, I cannot do this:
```
git clone https://github.com/my_repo/mobilecoin.git /tmp/mobilenode && cd /tmp/mobilenode && git checkout 0f09862109fa8c3749012ffed355eb25eed775d6
Cloning into '/tmp/mobilenode'...
remote: Enumerating objects: 14627, done.
remote: Total 14627 (delta 0), reused 0 (delta 0), pack-reused 14627
Receiving objects: 100% (14627/14627), 5.88 MiB | 6.74 MiB/s, done.
Resolving deltas: 100% (9015/9015), done.
fatal: reference is not a tree: 0f09862109fa8c3749012ffed355eb25eed775d6
```

Is there anything I am doing in a wrong way? 

It was an option for the previous versions. My assumption is, that it was not properly pushed on your side, but I may mistake.

**Comment by nick-mobilecoin** [comment]
What is the real url of `https://github.com/my_repo/mobilecoin.git`?
The reference is here, https://github.com/mobilecoinfoundation/mobilecoin/commits/0f09862109fa8c3749012ffed355eb25eed775d6

**Comment by fmira21** [comment]
@nick-mobilecoin 
Hm, now I understand:)
It's just a variable, but it resolved like `https://github.com/mobilecoin/mobilecoin.git`. My fault.

Thank you, your help was priceless!
