### ISSUE TITLE
CI should use the same docker entrypoint as mob tool to enter container

### ISSUE THREAD

**Issue by garbageslam** [mobilecoinfoundation/mobilecoin#2607]
Currently, github actions CI builds in our container, but doesn't use the docker entrypoint which was created for mob prompt.
This means that we can break the ability to build releases / run tests locally, without catching it in CI.

(Example: https://github.com/mobilecoinfoundation/mobilecoin/pull/2606)

We should use the same entrypoint we use for releases that we do when we build in CI.

**Comment by jgreat** [comment]
It does use the same entrypoint, it just doesn't use `./mob prompt` or provide the required ENV vars for activate the create user part.

I don't think it should.  GitHub actions does some funky stuff when it runs a container.  It writes over the user's home.  This is why there's all that wiring to put cargo/rust paths in /opt.  Trying to get a dynamic user creation to work in GHA is just going to be a recipe for pain.

**Comment by garbageslam** [comment]
Is there anything else we could do so that the issue nick ran into would have been caught by CI? What's the long term fix? Is it putting postgres in its own container?
