### ISSUE TITLE
Make it possible to unit test attested enclave calls like `client_propose_tx`

### ISSUE THREAD

**Issue by cbeck88** [mobilecoinfoundation/mobilecoin#2718]
Currently, enclave calls like `client_propose_tx` cannot be unit tested in crates like `mc-consensus-enclave-impl`.
This is because to invoke the call correctly, the caller must establish an AKE connection.

The mc-crypto-noise stuff can all be used just fine, but we fail because the enclave ake state does not have a verification report.

```
    #[test_with_logger]
    fn test_client_tx_propose_works(logger: Logger) {
        let mut rng = Hc128Rng::from_seed([1u8; 32]);

        let block_version = BlockVersion::MAX;
        let responder_id = Default::default();
        let fee_map = FeeMap::default();

        let enclave = SgxConsensusEnclave::new(logger.clone());
        let blockchain_config = BlockchainConfig {
            block_version,
            fee_map: fee_map.clone(),
            ..Default::default()
        };
        enclave
            .enclave_init(&responder_id, &responder_id, &None, blockchain_config)
            .unwrap();

        // First, create an encrypted connection from a client
        let initiator = Start::new(responder_id.to_string());
        let init_input = ClientInitiate::<X25519, Aes256Gcm, Sha512>::default();
        let (initiator, auth_request_output) = initiator.try_next(&mut rng, init_input).unwrap();

        let auth_request_msg = AuthMessage::from(auth_request_output);
        let (auth_response_msg, _client_session) =
            enclave.client_accept(auth_request_msg.into()).unwrap();
```

This fails at `enclave.client_accept`:

```
running 1 test
test tests::test_client_tx_propose_works ... FAILED

failures:

---- tests::test_client_tx_propose_works stdout ----
thread 'tests::test_client_tx_propose_works' panicked at 'called `Result::unwrap()` on an `Err` value: Attest(NoReportAvailable)', consensus/enclave/impl/src/lib.rs:1193:103
```

However, there is no way to obtain a report in the `mc-consensus-enclave-impl`, because none of this code is running in an enclave, even a simulation mode enclave. So setting `SGX_MODE=SW` is irrelevant to this.

We should redesign this code for testability so that we can actually test all of the public APIs of the business logic of the enclaves.

We think there is no good reason that all public APIs of `SgxConsensusEnclave` cannot be unit tested, and indeed, actually testing the public API is the most valuable thing we can do, since this is the API that actually matters.

This also relates to feedback that we got during Trail of Bits audit. The lack of unit tests of the consensus enclave boundary makes it hard to create fuzzing tests, but this is extremely important to do at the secure enclave boundary.

We think there is no "tradeoff" between testability and security -- we need to have both of these, and with a little imagination we can see several possible routes:

Possibilities:
* Create a test-only API that allows injecting an (empty) verification report into the `AkeEnclaveState` to get past this. (This is similar to what we did in the transaction builder to allow testing that TxOut sort order is being verified.)
* During attestation, make the `VerificationReport` optional, and if the enclave doesn't have one available, it just doesn't give one to the clients. For a normal client like `ThickClient`, if the `VerificationReport` is missing then attestation fails. In unit tests, we ignore the lack of a verification report.

**Comment by garbageslam** [comment]
As a side remark -- this issue is ultimately a lot more fundamental than `mc-consensus-enclave-impl` even. There is a ton of security critical code connected all the enclaves, like `mc-crypto-ake-enclave`, that has zero unit test coverage, and mostly cannot be unit tested at all because of this issue.

**Comment by garbageslam** [comment]
I was able to make a proper test that actually tests the public API by testing at the `mc-consensus-enclave` crate rather than the `mc-consensus-enclave-impl` crate:

https://github.com/mobilecoinfoundation/mobilecoin/pull/2670/files#r997458095

This may be a good way forward, maybe we should try to test most of the public API this way. We can share a lot of the enclave setup code.
