### ISSUE TITLE
Make fog-ledger also load blocks from postgres in batches

### ISSUE THREAD

**Issue by cbeck88** [mobilecoinfoundation/mobilecoin#2763]
We should develop an analogue of this PR: https://github.com/mobilecoinfoundation/mobilecoin/pull/2707

for fog-ledger server, otherwise eventually we will have the same problem there.

**Comment by jcape** [comment]
I thought fog-ledger used a local LMDB?

**Comment by cbeck88** [comment]
You're right, this ticket doesnt make sense, sorry
