### ISSUE TITLE
FLR is ready to deploy

### ISSUE THREAD

**Issue by jcape** [mobilecoinfoundation/mobilecoin#3174]
- [x] Discussions had with ops
- [x] Initial deployment completed by ops
- [ ] #3191

**Comment by jcape** [comment]
- [ ] Discussions had with ops
- [ ] Initial deployment completed by ops
- [ ] Any issues uncovered during ops development have been resolved

**Comment by jcape** [comment]
Ops needs to say we're good.

**Comment by aweis89** [comment]
> @aweis89 Is there anything else that you think needs to be addressed before this can be marked as complete?

Not that I could think of at the moment. However a really nice to have would be for the router to expose the total block count, either via GRPC or even just a metric. But i don't think that should block this being marked complete

**Comment by jcape** [comment]
Dev work is seemingly complete, closing this.
