### ISSUE TITLE
V4.1 - fog missing Prometheus metric duration buckets for ledger and view paths

### ISSUE THREAD

**Issue by jgreat** [mobilecoinfoundation/mobilecoin#3281]
Looks like duration_count buckets are missing some entries in v4.1. I see a `ledger_server_grpc_duration_count`, but its only showing admin and healthcheck paths.

v4.0 shows timing buckets for:

- fog_ledger.FogBlockAPI.GetBlocks
- fog_ledger.FogMerkleProofAPI.GetOputputs
- fog_ledger.FogKeyImageAPI.Auth
- fog_ledger.FogUntrustedTxOutApi.GetTxOuts
- fog_ledger.FogKeyImageAPI.CheckKeyImages
- fog_ledger.FogMerkleProofAPI.Auth
- fog_view.FogViewAPI.Auth
- fog_view.FogViewAPI.Query 

v4.0 example of ledger in grafana:

![image](https://user-images.githubusercontent.com/5324639/227390439-56640708-93c1-44de-96e0-389b34a6666c.png)

**Comment by varsha888** [comment]
https://github.com/mobilecoinfoundation/mobilecoin/pull/3322
