### ISSUE TITLE
Handle empty array of measurements

### ISSUE THREAD

**Issue by nick-mobilecoin** [mobilecoinfoundation/mobilecoin#3374]
Currently (#3368) measurements are passed as a `Vec<>` meaning one of the measurements needs to match. However if the measurements are empty, there is no attempt to ensure measurements are verified.
It seems like it should result in an error if someone passes in an empty list of measurements,this way they don't inadvertently allow any and all enclaves which happen to be signed by the trust root (intel).

Some interfaces like watcher, https://github.com/mobilecoinfoundation/mobilecoin/blob/781fd36cc916e4a20ee5ec95a1973a935437893d/watcher/src/verification_reports_collector.rs#L76, don't wish to verify reports with measurements (MRSIGNER or MRENCLAVE).
It may be that this only needs the reports and was leveraging the common verify interface to get at them.

**Comment by eranrund** [comment]
> It may be that this only needs the reports and was leveraging the common verify interface to get at them.

Yes, I believe thats the case.

**Comment by nick-mobilecoin** [comment]
The `TrustedIdentitiesVerifier` will fail if there are no identities. Clients that wish to verify with no identities need to create their own verifier that doesn't use `TrustedIdentitiesVerifier`.
