### ISSUE TITLE
Long pending transaction: Funding eUSD with ERG from Moby app

### ISSUE THREAD

**Issue by 0xOdy** [mobilecoinfoundation/mobilecoin#3529]
Hello,

Installed the app (Moby app ) this morning to try its features, and see if we can use it reliably for any payment.

Sent fund from signal to moby app worked great, the problem is when I try to fund eUSD with the MOB i transferred from the signal application.

sent the fund  4h ago, but the transaction is still pending ...

The fund is not important, it  was a negligible amount.

**Comment by nick-mobilecoin** [comment]
Hi @0xOdy, 
Thanks for trying out the app and reporting an issue.

Unfortunately this repository isn't for the Moby app. 
Moby issues can be reported to support@moby.app 
One can also:
1. click on the Person Icon in the top left of the app
2. Click the support menu option
3. Click contact support, or copy the email link there.

We do appreciate you taking the time to report the issue.
I can understand it may be a bit frustrating to be redirected, but more information will likely be needed about the transaction and your moby user that would best be handled by the dedicated support email path.
