### ISSUE TITLE
What is the state of identity-on-chain?

### ISSUE THREAD

**Issue by nkosi23** [mobilecoinfoundation/mobilecoin#3948]
Hello!

I am wondering, what is the state of identity-on-chain features for mobilecoin? Is there any approach available today for users?

As far as I am concerned, the use case I am interested in is the following: I want to confirm that a user is the owner of a token address. The ideal approach I want to follow, is to require the user to send a couple of payments for a specific amount to an address I control from the address for which I want him to prove his ownership.

For example, I'd require the customer to send 0.0002 and 0.0016 MOB. That way, I can assume with high confidence that if the customer knows these 2 secrets + my address, data that I have only disclosed to this specific individual, the sending address is indeed controlled by this individual.

My understanding is that the privacy features of the Mobilecoin blockchain get in the way of this approach since addresses are randomized for every transaction, and I would therefore not be able to tie the base address communicated to me by the user (whose ownership is being confirmed), to the sending address listed in the transaction.

If this is indeed the case, are there alternative approaches that can be used today (ideally through the full-service API)?

Many thanks for the awesome work you have done.

**Comment by nick-mobilecoin** [comment]
If I'm understanding your question correctly I think it's covered by https://github.com/mobilecoinfoundation/mcips/blob/main/text/0004-recoverable-transaction-history.md

The [validate-sender-memo](https://mobilecoin.gitbook.io/full-service-api/api-endpoints/v2/transaction/txo/memo/validate-sender-memo#response-1) can be used to validate the sender. Note that this cannot be used from a view only account.
It looks like fullservice will always provide the memo when using [build-transaction](https://mobilecoin.gitbook.io/full-service-api/api-endpoints/v2/transaction/transaction/build_transaction) or similar
