### ISSUE TITLE
SGX crates and GPL license

### ISSUE THREAD

**Issue by mspiegel** [mobilecoinfoundation/mobilecoin#4003]
Hello,

The SGX crates contain code derived from the Rust standard library and Apache Teaclave SGK SDK. The derivates can’t be relicensed with a GPL license.

**Comment by cbeck88** [comment]
Are you sure about that?

c.f. https://en.wikipedia.org/wiki/Apache_License

> The Apache Software Foundation and the [Free Software Foundation](https://en.wikipedia.org/wiki/Free_Software_Foundation) agree that the Apache License 2.0 is a [free software license](https://en.wikipedia.org/wiki/Free_software_license), compatible with the [GNU General Public License](https://en.wikipedia.org/wiki/GNU_General_Public_License)[[5]](https://en.wikipedia.org/wiki/Apache_License#cite_note-Apache_licenses-5) (GPL) version 3,[[2]](https://en.wikipedia.org/wiki/Apache_License#cite_note-fsflist-2) meaning that code under [GPLv3](https://en.wikipedia.org/wiki/GNU_General_Public_License#Version_3) and Apache License 2.0 can be combined, as long as the resulting software is licensed under the GPLv3.[[6]](https://en.wikipedia.org/wiki/Apache_License#cite_note-6)

**Comment by mspiegel** [comment]
My apologies. I have a need for a subset of the Apache Teaclave SGX SDK v1.0 that can be used with a modern Rust compiler. The parts of Teaclave that do not require `feature(rustc_private)`. For my use-case I need the code to remain Apache Licensed. I will not use mobilecoin SGX crates to respect both GPL and Apache licenses.
