### ISSUE TITLE
When i run `cargo test`  under ./api, will error

### ISSUE THREAD

**Issue by jadeydi** [mobilecoinfoundation/mobilecoin#548]
cd ~/mobilecoin/api  

`cargo build` works ok

`cargo test` will get the following errors:

   Compiling mc-common v1.0.0 (/Users/x/Projects/mobilecoin/common)
   Compiling mc-util-test-helper v1.0.0 (/Users/x/Projects/mobilecoin/util/test-helper)
error[E0433]: failed to resolve: use of undeclared type or module `std`
 --> common/src/panic_handler.rs:5:5
  |
5 | use std::{
  |     ^^^ use of undeclared type or module `std`

error[E0433]: failed to resolve: use of undeclared type or module `std`
   --> common/src/logger/mod.rs:101:13
    |
101 |         use std::time::Instant;
    |             ^^^ use of undeclared type or module `std`

.....

error[E0599]: no method named `to_string` found for reference `&'static str` in the current scope
  --> common/src/panic_handler.rs:22:65
   |
22 |     let process_name = env::args().next().unwrap_or_else(|| "?".to_string());
   |                                                                 ^^^^^^^^^ method not found in `&'static str`
   |
   = help: items from traits can only be used if the trait is in scope
   = note: the following trait is implemented but not in scope; perhaps add a `use` for it:
           `use crate::alloc::string::ToString;`

error: aborting due to 20 previous errors

Some errors have detailed explanations: E0412, E0432, E0433, E0599.
For more information about an error, try `rustc --explain E0412`.
error: could not compile `mc-common`.

**Comment by eranrund** [comment]
I believe this was fixed in https://github.com/mobilecoinfoundation/mobilecoin/commit/c26f3b03d0839afe126b0e93233c56edae68b3ea
