### ISSUE TITLE
[feature request] support `GetProcessedBlock` in mobilecoind-json

### ISSUE THREAD

**Issue by Ljzn** [mobilecoinfoundation/mobilecoin#563]
`GetProcessedBlock` is an essential API for exchange integration, but I can not find that in the document of mobilecoind-json. Would you mind wrapping this gRPC route in mobilecoind-json?

**Comment by sugargoat** [comment]
Hi @Ljzn!

The processed block endpoint is available in mobilecoind-json, at the route specified here: [processed-block](https://github.com/mobilecoinfoundation/mobilecoin/blob/master/mobilecoind-json/src/bin/main.rs#L600). 

We will update the README documentation to provide an example of using this endpoint.
