### ISSUE TITLE
Setuid purse for no reason.

### ISSUE THREAD

**Issue by posix4e** [mobilecoinfoundation/mobilecoin#579]
As I have brought up on numerous occasions on the secret electron slack, shipping Linux binaries setuid is just bad practice. modern linuxes support fine-grained namespaces so we don't need to have the application (chrome) start as root. The problem is that if a bad library is slipped in the LD_LIRBARY_PATH you could potentially load some dynamic code that hacks the machine as root. In addition, as the purse isn't open-source, I'm not a super fan of installing setuid binaries as I can't audit them.

In the meantime, I'd suggest
1) DIsabling the setuid bit as a part of the deb package creation immediately.  I've already tested it on my machine and it doesn't need chrome to be setuid for the purse to run
2) Providing an alternative legacy package if people don't want to enable namespaces. It's easy enough to just create two debs
3) Provide instructions for archlinux users and others on how to enable namespaces, it's already needed for tools like docker and is pretty standard.

**Comment by sugargoat** [comment]
Thank you! The desktop wallet app is still very much pre-release beta, and we are currently working through the security checklist (see: [Electron Security Checklist](https://doyensec.com/resources/us-17-Carettoni-Electronegativity-A-Study-Of-Electron-Security-wp.pdf)). Any other observations on wallet security are very welcome.
