### ISSUE TITLE
An alternative fix for .cargo/config.toml

### ISSUE THREAD

**Issue by posix4e** [mobilecoinfoundation/mobilecoin#580]
I noticed that in https://github.com/mobilecoinfoundation/mobilecoin/blob/24c9dcdf14440d6d285eef79dab611871646aaad/.cargo/config#L4

we hard code the architecture flags to some very particular things
I wonder if instead we could take an approach like 
https://github.com/shadowsocks/shadowsocks-rust/commit/4fd4ac5bbe29d9294b15abb422d82108e8a3a2fc
with envvars. We've already done so for things like SGX. Happy to do the work if this sounds good.

**Comment by remoun** [comment]
It seems removing the spaces makes the buildflags override work. I'll send a PR.

**Comment by jcape** [comment]
This may not be easily fixable
