### ISSUE TITLE
Tidy up the python

### ISSUE THREAD

**Issue by posix4e** [mobilecoinfoundation/mobilecoin#592]
Our python code could use some love. Here are my plans

- [x] Add a linter to the container . I really love black cause it's fast and opinionated
- [ ] Push out new docker images with the linter in it.
- [ ] Remove some of the extra unneeded stuff from the container
- [ ] Upgrade the scripts to use the new docker image.
- [ ] Actually use the linter in the ci
- [ ] Consider adding something like mypy or other logic checkers
- [ ] A once through to look for bad smells or needed tests

**Comment by posix4e** [comment]
I don't think we really have to do anything to push out new containers, but I've never done it before. It's going to be interesting!

**Comment by posix4e** [comment]
It seems we reference the docker repo in the code directly
.mobconf:repository = gcr.io/mobilenode-211420/
mob:repository = storage for remote images from farm e.g. gcr.io/mobilenode-211420 (optional)
 Perhaps we should document that as the official docker repo? 

Also, there's two references two the docker image
.circleci/config.yml:  builder-install: &builder-install gcr.io/mobilenode-211420/builder-install:1_13
jenkins/build-pod.yaml:      image: gcr.io/mobilenode-211420/builder-install:1_13
. Perhaps we can add a document on updating the docker image and how to get the info from circle ci? BTW, how does that work currently?

**Comment by garbageslam** [comment]
there is some documentation around this but it isn't in the public repo, we can try to improve this

**Comment by posix4e** [comment]
> there is some documentation around this but it isn't in the public repo, we can try to improve this

Sure. It looks like we aren't pushing a docker container as a part of CI? Do we want this in the public ci?

**Comment by posix4e** [comment]
@kylefleming I saw you merged #590 Thanks! Any idea how we update the .cericleci/config.yml and jenkins/build-pod.yaml to point to a new image?

**Comment by kylefleming** [comment]
> @kylefleming I saw you merged #590 Thanks! Any idea how we update the .cericleci/config.yml and jenkins/build-pod.yaml to point to a new image?

Someone in the org will need to push a new image to Google Cloud. It's a manual process at the moment. Once that's done, then it's just a matter of updating the docker tags (https://github.com/mobilecoinfoundation/mobilecoin/pull/567 can be used as a reference).

**Comment by posix4e** [comment]
@kylefleming  @rjwalters  Oh. Any reason why we shouldn't just hook it up to a public docker.io account and have circle push it on release?
