### ISSUE TITLE
link to download client goes to 404

### ISSUE THREAD

**Issue by paxblueribbon** [mobilecoinfoundation/mobilecoin#599]
in test.md the links to the linux and mac downloads go to 404s, I can't find the release folder that it should be switched to or I'd submit this as a pull request.

**Comment by sugargoat** [comment]
Thanks for reporting! We are working out better ways of distributing software for TestNet vs MainNet. For now, the latest TestNet binaries can be found in the [assets on this Release](https://github.com/mobilecoinfoundation/mobilecoin/releases/tag/v1.0.0-pre8.2).

We'll update the README to not link to "latest" soon.
