### ISSUE TITLE
Build failed on Macos

### ISSUE THREAD

**Issue by islishude** [mobilecoinfoundation/mobilecoin#760]
Run `SGX_MODE=HW IAS_MODE=DEV cargo build` and get flowing

```
error on line 49 of /project/github.com/mobilecoinfoundation/mobilecoin/crypto/x509/test-vectors/openssl.cnf
4493999788:error:0EFFF068:configuration file routines:CRYPTO_internal:variable has no value:/AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-56.60.2/libressl-2.8/crypto/conf/conf_def.c:563:line 49
```

**Comment by jcape** [comment]
You'll need to `brew install openssl`, and ensure it's in your command-line. The libreSSL that ships with MacOS X doesn't support Ed25519 or a bunch of config-file (arguable) misfeatures we're using when generating test certs.
