### ISSUE TITLE
mobilecoind should reject `mcp://` URLs

### ISSUE THREAD

**Issue by jcape** [mobilecoinfoundation/mobilecoin#828]
As discussed in #827, mobilecoind allows the user to specify `mcp://` URLs for peers, which validator nodes rightly reject. This should never be the case.

**Comment by remoun** [comment]
Are we sure `mobilecoind` accepts `mcp://` URLs for peers?

I see the code  explicitly restricts the `--peer` flag to a `ConsensusClientUri`: https://github.com/mobilecoinfoundation/mobilecoin/blob/ac6b2a08ff7fceaadd86fc852c920b8a1935e6ed/mobilecoind/src/config.rs#L257

And there are tests that enforce that ClientUri does not accept `mcp://` URLs:
https://github.com/mobilecoinfoundation/mobilecoin/blob/8b61588c09d64d58830a18d1f7f00dd12fa3e53b/util/uri/src/lib.rs#L258
