### ISSUE TITLE
gRPC with alternative gRPC frameworks

### ISSUE THREAD

**Issue by cndolo** [mobilecoinfoundation/mobilecoin#856]
Hi there.

I would like to use the consensus gRPC API with other tools such as [tonic](https://github.com/hyperium/tonic) or [grpc-rs](https://github.com/tikv/grpc-rs) and not grpcurl. Do you have any experience with this? 
I have been successful in generating the corresponding Rust code (with protoc-grpcio when using the latter) but not able to connect to the servers using their host-names, e.g. `node1.test.mobilecoin.com:443`.  An error that has shown up on different occasions stated that the URL was wrong due to a missing scheme.
Have you by any chance tested the API with other software?

**Comment by jcape** [comment]
The short answer is "yes": the mobile SDKs use native gRPC libraries for [iOS](https://github.com/mobilecoinofficial/MobileCoin-Swift) and [Android](https://github.com/mobilecoinofficial/android-sdk), though they continue to use rust for, e.g. attestation/key exchange and transaction construction.

Rust-based apps (mobilecoind, watcher, full-service) are using [a fork of `grpc-rs`](https://github.com/mobilecoinofficial/grpc-rs/tree/client-unary-metadata), mediated through the `mc-api` and `mc-consensus-api` crates in this repo.

The fork includes support for "initial metadata" (HTTP cookies), which is necessary to support server-side load balancing. That is, the "auth" call, which establishes a secure channel, and subsequent "propose-tx" calls must go to the same enclave, which requires something a load balancer can "add" to the stream, in this case cookies. We're working with the `grpc-rs` developers to make that support [suitable for upstream inclusion](https://github.com/tikv/grpc-rs/issues/460).

**Comment by cndolo** [comment]
Thanks for the pointers.
I have now switched to your fork and looked at the code as well, which has left me with the code snippet below. 
It seems like the `ChannelBuilder` is able to open a gRPC connection to node (based on the output), however, the RPCs fail with: ` failed to connect to all addresses`. Should the code below be work?

```
fn main() {                                                                           
    let env = Arc::new(EnvBuilder::new().build());                                    
    let uri = ClientUri::from_str("insecure-mc://node2.test.mobilecoin.com:443").expect("error converting to ClientUri");
    println!("uri {:?}", uri);
    let logger = mc_common::logger::create_test_logger(String::from("wtf"));
    let ch = ChannelBuilder::default_channel_builder(env).connect_to_uri(&uri, &logger);
    let blockchain_client = BlockchainApiClient::new(ch.clone());

    let block_reply = blockchain_client.get_last_block_info(&empty::Empty::default()).expect("rpc failure");
    println!("got reply {:?}", reply.get_index());
} 
```
returns with 

```
uri Uri { url: Url { scheme: "insecure-mc", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("node2.test.mobilecoin.com")), port: Some(443), path: "/", query: None, fragment: None }, host: "node2.test.mobilecoin.com", port: 443, use_tls: false, username: "", password: "", _scheme: PhantomData }
2021-07-16 14:52:47.788540851 UTC WARN Creating insecure gRPC connection to node2.test.mobilecoin.com:443, mc.test_name: wtf, mc.module: mc_util_grpc::grpcio_extensions, mc.src: /home/cndolo/.cargo/git/checkouts/mobilecoin-03eff4a95c1d8436/599ec17/util/grpc/src/grpcio_extensions.rs:47
thread 'main' panicked at 'rpc failure: RpcFailure(RpcStatus { code: 14-UNAVAILABLE, message: "failed to connect to all addresses", details: [] })', src/main.rs:28:87
```

Some background on why I am keen on doing this in Rust and not using grpcurl: I would like to deserialise the responses into original type and proceed from there. It therefore seems(?) easier to have the responses as bytes in Rust data structures as opposed to the JSON data structures grpcurl returns.

**Comment by eranrund** [comment]
Hello,

You are trying to use `insecure-mc://`, which implies plaintext (as opposed to TLS). Can you try `mc://node2.test.mobilecoin.com:443`?

**Comment by cndolo** [comment]
I tried that too, but got the following 404 error that I wasn't sure what to make of:
```
thread 'main' panicked at 'rpc failure: RpcFailure(RpcStatus { code: 12-UNIMPLEMENTED, message: "Received http2 header with status: 404", details: [] })', src/main.rs:30:75
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by eranrund** [comment]
This is working fine for me - are you running the most recent `master`?

For reference, here's the code that I tested with:
```
use grpcio::{ChannelBuilder, EnvBuilder};
use mc_consensus_api::{consensus_common_grpc::BlockchainApiClient, empty};
use mc_util_grpc::ConnectionUriGrpcioChannel;
use mc_util_uri::ConsensusClientUri as ClientUri;
use std::{str::FromStr, sync::Arc};

fn main() {
    let env = Arc::new(EnvBuilder::new().build());
    let uri = ClientUri::from_str("mc://node2.test.mobilecoin.com:443")
        .expect("error converting to ClientUri");
    println!("uri {:?}", uri);
    let logger = mc_common::logger::create_test_logger(String::from("wtf"));
    let ch = ChannelBuilder::default_channel_builder(env).connect_to_uri(&uri, &logger);
    let blockchain_client = BlockchainApiClient::new(ch.clone());

    let block_reply = blockchain_client
        .get_last_block_info(&empty::Empty::default())
        .expect("rpc failure");
    println!("got reply {:?}", block_reply.get_index());
}
```

And the output:
```
uri Uri { url: "mc://node2.test.mobilecoin.com:443/", host: "node2.test.mobilecoin.com", port: 443, use_tls: true, username: "", password: "", _scheme: PhantomData }
got reply 160744
```

**Comment by cndolo** [comment]
> This is working fine for me - are you running the most recent master?

Yes. However, I had been using the sources generated locally by `protoc-grpcio`. Switching to those provided `mc-consensus-api` has produced the same output - I didn't expect that would make a difference. Thank you!

**Comment by eranrund** [comment]
> > This is working fine for me - are you running the most recent master?
> 
> Yes. However, I had been using the sources generated locally by `protoc-grpcio`. Switching to those provided `mc-consensus-api` has produced the same output - I didn't expect that would make a difference. Thank you!

I am not sure why that would make a difference, but glad it is working for you!
