### ISSUE TITLE
Make memos mandatory

### ISSUE THREAD

**Issue by garbageslam** [mobilecoinfoundation/mobilecoin#905]
In our release plan for the encrypted memos feature, we will do one release where memos are optional, and in a subsequent release, the memos will be mandatory for every transaction output.

This is intended to make the upgrade path easier for clients.

(See MCIP #3 for details on encrypted memos feature https://github.com/mobilecoinfoundation/mcips/pull/3)

This ticket tracks the task of making the memos mandatory.

**Comment by UkoeHB** [comment]
Protocol rules? Are you planning to write an MCIP?

**Comment by garbageslam** [comment]
The in-flight mcip proposes that the memos are mandatory.

> The `e_memo` field shall appear on every MobileCoin TxOut, starting with BLOCK_VERSION = 1.

But to accommodate a graceful update, we determined that there has to be a transitional period where they are optional, because we can't force all the clients to update simulatenousky with the servers.

I don't think we need an additional mcip for this but we could update the mcip to describe that there is an interim period in which they are optional and in a later consensus release they become mandatory.

Thanks for pointing this out. The optional thing is not in trunk yet, it is an in-flight PR.

**Comment by jcape** [comment]
Superceeded by mobilecoinfoundation/mcips#26
